name: Build, Test, and Analyze

on:
  push:
    branches:
      - main

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    container: mntmtt/sourcevaultdev:latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v4
        with:
          # Fetch all history for all branches. This is required for SonarQube's analysis.
          fetch-depth: 0

      - name: Configure and Build Project
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS=--coverage
          cmake --build build -j$(nproc)

      - name: Run Tests & Generate Coverage
        run: |
          cd build
          ctest --extra-verbose
          cd ..

      - name: Run SonarQube Scanner
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}